### ISSUE TITLE
Update Deploy on Fly.io section of readme

### ISSUE THREAD

**Issue by andie787** [fauna-labs/go-gin-fly-io-starter#1]
1. The FLy.io deploy process has changed and has a UI component now, so updates are required to the readme for this repo and the other example repos.
You'll want to test with `fly launch --no-deploy` to see the changes. That way you can still  add the secret before running `fly deploy`. 

2. Also, the way to scale into other regions needs an update. See this PR: https://github.com/superfly/docs/pull/1235

**Comment by zeekhoo** [comment]
Thanks suggestions. README has been updated.
